approvals:
  # check will fail if there is no approval
  minimum: 1     # optional
  groups:        # optional
    - name: main
      minimum: 2 # optional
      from:
        person:
          - sergioko747
          - sergioko757
        team:
          - s737team
