approvals:
  # check will fail if there is no approval
  minimum: 1     # optional replicates GitHub branch protection
  groups:        # optional
    - name: main
      minimum: 1 # optional
      from:
        persons:
          - sergioko747
          # - sergioko757
        teams:
