# approvals:
#   # check will fail if there is no approval
#   minimum: 1     # optional replicates GitHub branch protection
#   groups:        # optional
#     - name: main
#       minimum: 1 # optional
#       from:
#         persons:
#           - sergioko747
#           - sergioko757
#         teams:

approval_groups:
  - name: HEADS
    condition: 👤
    check_type: pr_diff_body
    min_approvals: 2
    users:
    teams:
      - s737team
  - name: BAGS
    condition: '/👜.*(\n^[\+|\-].*)|^[\+|\-].*👜/gm'
    check_type: pr_diff_body
    min_approvals: 1
    users:
      - sergioko747
    teams:
