on:
  push:
  pull_request:
  pull_request_review:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: list reviviewers
        run: |
          USERS_REVIEW_REQUESTED_FROM=$(cat $GITHUB_EVENT_PATH | jq '.pull_request.requested_reviewers | map("@" + .login) | join(" ")')
          echo "Reviewers: $USERS_REVIEW_REQUESTED_FROM"
      - name: Hello world action step
        id: hello
        uses: s737testOrg/hello-world-javascript-action@v1.1
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"