name: Playground

on:
  push:

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pr-custom-review
        run: |
          echo "------------------SET--------------------"
          set
          echo "------------------ENV--------------------"
          env
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: script-test
        run: |
          echo "My ORG is --- $GITHUB_REPOSITORY_OWNER ---"
          echo "test curl"
          curl "https://github.com/$GITHUB_REPOSITORY_OWNER/gha_test/blob/6690b1d8bd98b40a302a8e9d07c93a0c28d5e4ca/testdir/testfile3"
          echo "test ENV from script"
          ls
