name: Playground

on:
  push:

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pr-custom-review
        run: |
          echo "------------------SET--------------------"
          set
          echo "------------------ENV--------------------"
          env
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: script-test
        run: |
          echo "------------------My ORG is --- $GITHUB_REPOSITORY_OWNER ---"
          echo "------------------test curl------------------"
          curl "https://github.com/$GITHUB_REPOSITORY_OWNER/gha_test/master/testdir/testfile3"
          echo "------------------test ENV from script------------------"
          ls -al
          bash ./test_script/test.sh
