name: PR Custom Review Status

on:
  pull_request:
    branches:
      - master
      - main
    types:
      - opened
      - reopened
      - synchronize
      - review_requested
      - review_request_removed
  pull_request_review:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pr-custom-review
        uses: sergejparity/pr-custom-review@enhance-builtin-check
        with:
          token: ${{ secrets.GHA_TOKEN }}
          locks-review-team: s737team
          team-leads-team: s737team
